---
- name: test
  hosts: all
  become: yes
  become_user: docker
  gather_facts: yes

  tasks:


  

  - name: Nginx Bitch!
    community.docker.docker_container:
     name: myapplication
     image: nginx
     state: started
     restart: yes
     ports:
      - "80:80"
     env:
         SECRET_KEY: "w"
         BOOLEAN_KEY: "yes"



  


    
