- name: install docker
  hosts: all
  become: yes
  gather_facts: yes
  tasks:

    ######   Debian key and repo   ######
   
    - name: add GPG key for Debian
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: add docker repository to apt
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
      when: ansible_facts['os_family'] == "Debian"

###########   RedHat utils and repo #######

    - name: install a dependency
      package:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - yum-utils
      when: ansible_facts['os_family'] == "RedHat"

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
      when: ansible_facts['os_family'] == "RedHat"

    
###### Start and install docker ############


    - name: Install Docker on RedHat
      package:
        name: docker-ce
        state: latest

    - name: Docker start and enable
      systemd:
        name: docker
        state: started
        enabled: true


   
     


      
