- name: install docker
  hosts: all
  become: yes
  gather_facts: yes
  tasks:


    - name: install a dependency

      package:
        name: "{{item}}"
        state: present
       
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
      when: ansible_facts['os_family'] == "Debian"


    - name: add GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: add docker repository to apt
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
      when: ansible_facts['os_family'] == "Debian"


    - name: install docker
      package:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      when: ansible_facts['os_family'] == "Debian"


###########   RED HAT OS #####

    - name: install a dependency
      yum:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - yum-utils
      when: ansible_facts['os_family'] == "RedHat"


    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
      when: ansible_facts['os_family'] == "RedHat"

    - name: Install Docker on RedHat
      package:
        name: docker-ce
        state: latest
      when: ansible_facts['os_family'] == "RedHat"  




######START DOCKER #####


    - name: docker start and enable
      systemd:
        name: docker
        state: started
        enabled: true



   

    

   
     


      
